DEMO_ROWS = [
    {
        "segment": "Freelance designers",
        "pain_point": "Hard to present design value to clients",
        "competitor": "Canva",
        "feature": "Presentation templates",
        "pricing_tier": "Freemium",
        "opportunity": "Value-based design case builder",
        "severity": 8,
        "willingness_to_pay": 7,
        "competition_intensity": 5,
        "evidence_count": 12,
    },
    {
        "segment": "Startup founders",
        "pain_point": "Hard to choose MVP scope",
        "competitor": "Notion",
        "feature": "Templates",
        "pricing_tier": "Freemium",
        "opportunity": "MVP scope decision canvas",
        "severity": 9,
        "willingness_to_pay": 8,
        "competition_intensity": 4,
        "evidence_count": 15,
    },
    {
        "segment": "Product managers",
        "pain_point": "Roadmap not linked to strategy",
        "competitor": "Aha",
        "feature": "Roadmap planning",
        "pricing_tier": "Paid",
        "opportunity": "Strategy-to-roadmap visual map",
        "severity": 9,
        "willingness_to_pay": 8,
        "competition_intensity": 7,
        "evidence_count": 10,
    },
    {
        "segment": "Product managers",
        "pain_point": "Hard to defend roadmap to stakeholders",
        "competitor": "Productboard",
        "feature": "Prioritization",
        "pricing_tier": "Paid",
        "opportunity": "Stakeholder alignment canvas",
        "severity": 8,
        "willingness_to_pay": 7,
        "competition_intensity": 6,
        "evidence_count": 9,
    },
    {
        "segment": "UX researchers",
        "pain_point": "Insights scattered across tools",
        "competitor": "Dovetail",
        "feature": "Research repository",
        "pricing_tier": "Paid",
        "opportunity": "Insight-to-opportunity map",
        "severity": 8,
        "willingness_to_pay": 7,
        "competition_intensity": 6,
        "evidence_count": 9,
    },
    {
        "segment": "UX researchers",
        "pain_point": "Insights ignored by product teams",
        "competitor": "Dovetail",
        "feature": "Sharing",
        "pricing_tier": "Paid",
        "opportunity": "Insight impact tracker",
        "severity": 7,
        "willingness_to_pay": 6,
        "competition_intensity": 4,
        "evidence_count": 7,
    },
    {
        "segment": "Indie hackers",
        "pain_point": "Hard to find market gaps",
        "competitor": "Product Hunt",
        "feature": "Discovery",
        "pricing_tier": "Free",
        "opportunity": "Market gap visualizer",
        "severity": 7,
        "willingness_to_pay": 6,
        "competition_intensity": 3,
        "evidence_count": 8,
    },
    {
        "segment": "Indie hackers",
        "pain_point": "Hard to validate idea before building",
        "competitor": "Reddit",
        "feature": "Communities",
        "pricing_tier": "Free",
        "opportunity": "Lightweight validation board",
        "severity": 8,
        "willingness_to_pay": 5,
        "competition_intensity": 4,
        "evidence_count": 6,
    },
    {
        "segment": "Design leads",
        "pain_point": "Design debt is hard to explain",
        "competitor": "Figma",
        "feature": "Design system",
        "pricing_tier": "Paid",
        "opportunity": "Design debt impact map",
        "severity": 8,
        "willingness_to_pay": 7,
        "competition_intensity": 5,
        "evidence_count": 11,
    },
    {
        "segment": "Design leads",
        "pain_point": "Hard to measure design team impact",
        "competitor": "Figma",
        "feature": "Analytics",
        "pricing_tier": "Enterprise",
        "opportunity": "Design impact dashboard",
        "severity": 7,
        "willingness_to_pay": 7,
        "competition_intensity": 4,
        "evidence_count": 8,
    },
    {
        "segment": "Heads of Product",
        "pain_point": "No visibility into bets across squads",
        "competitor": "Aha",
        "feature": "Portfolio view",
        "pricing_tier": "Enterprise",
        "opportunity": "Cross-squad bets map",
        "severity": 9,
        "willingness_to_pay": 9,
        "competition_intensity": 5,
        "evidence_count": 13,
    },
    {
        "segment": "Heads of Product",
        "pain_point": "Strategy doesn't reach squads",
        "competitor": "Productboard",
        "feature": "Strategy planning",
        "pricing_tier": "Enterprise",
        "opportunity": "Strategy cascade tool",
        "severity": 8,
        "willingness_to_pay": 8,
        "competition_intensity": 6,
        "evidence_count": 10,
    },
]
