// Renders an opportunity brief (response from /opportunities/:id/brief) as
// clean Markdown suitable for pasting into Notion, Linear, Slack, etc.

function bar(score) {
  const filled = Math.round((score / 100) * 20);
  return "█".repeat(filled) + "░".repeat(20 - filled);
}

export function briefToMarkdown(brief) {
  const lines = [];
  const sb = brief.score_block;

  lines.push(`# ${brief.title}`);
  lines.push("");
  lines.push(`> ${brief.one_liner}`);
  lines.push("");
  lines.push(`**Score:** ${sb.score}/100 · **Decision:** ${sb.bucket_label}`);
  lines.push("");
  lines.push("```");
  lines.push(`${bar(sb.score)} ${sb.score}/100`);
  lines.push("```");
  lines.push("");

  lines.push("## Score breakdown");
  lines.push("");
  lines.push("| Component | Raw | Contribution |");
  lines.push("|---|---|---|");
  for (const c of sb.components) {
    const raw =
      c.raw_value_max != null
        ? `${c.raw_value} / ${c.raw_value_max}`
        : String(c.raw_value);
    lines.push(`| ${c.label} | ${raw} | +${c.contribution} |`);
  }
  lines.push("");
  lines.push(`_Formula: ${sb.formula_note}_`);
  lines.push("");

  if (brief.top_signals?.length) {
    lines.push(`## Top supporting signals (${brief.total_signals} total)`);
    lines.push("");
    for (const s of brief.top_signals) {
      lines.push(`- **${s.source_type}** — ${s.note || "(no note)"}`);
      lines.push(`  ${s.url}`);
    }
    lines.push("");
  }

  if (brief.competitive_landscape?.length) {
    lines.push("## Competitive landscape");
    lines.push("");
    for (const c of brief.competitive_landscape) {
      lines.push(`### ${c.competitor}`);
      lines.push(`- Covers in this segment: ${c.features_covered.join(", ") || "—"}`);
      lines.push(
        `- Does not address: ${
          c.pains_not_addressed.length
            ? c.pains_not_addressed.map((p) => `"${p}"`).join("; ")
            : "fully covers the known pains in this segment"
        }`
      );
      lines.push("");
    }
  }

  if (brief.open_questions?.length) {
    lines.push("## Open questions / risks");
    lines.push("");
    for (const q of brief.open_questions) {
      lines.push(`- ${q}`);
    }
    lines.push("");
  }

  lines.push("## Recommended next step");
  lines.push("");
  lines.push(`> ${brief.next_step.recommendation}`);
  lines.push("");
  lines.push("---");
  lines.push("_Generated by Market Opportunity Map_");

  return lines.join("\n");
}
